[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.20"
optimizer = true
optimizer_runs = 200

[rpc_endpoints]
polygon = "${POLYGON_RPC_URL}"
amoy = "${AMOY_RPC_URL}"
bsc = "${BSC_RPC_URL}"
bsc_testnet = "${BSC_TESTNET_RPC_URL}"

[etherscan]
polygon = { key = "${POLYGONSCAN_API_KEY}" }
amoy = { key = "${POLYGONSCAN_API_KEY}" }
bsc = { key = "${BSCSCAN_API_KEY}", url = "https://api.bscscan.com/api" }
bsc_testnet = { key = "${BSCSCAN_API_KEY}", url = "https://api-testnet.bscscan.com/api" }
